export const ADD_FAVOURITE = 'ADD_FAVOURITE'
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE'
export const FILTER = 'FILTER'
export const ORDER = 'ORDER'
export const GET_FAVOURITE = 'GET_FAVOURITE'